; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Oct 19 2020 17:21:39 GMT-0700 (Pacific Daylight Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


