; tpost1.g
; called after tool 1 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.3 on Wed Jul 08 2020 18:44:59 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P1

